export default [
  {
    id: "123",
    firstName: "John",
    middleName: null,
    lastName: "Doe",
    addressLine1: "33501 1ST WAY S",
    addressLine2: null,
    city: "Federal Way",
    state: "WA",
    zipCode: "98003",
    specialty: "Podiatric Medicine & Surgery Service Providers|Podiatrist",
    reviews: [],
    payments: [
      {
        id: "471363571",
        doctorId: "123",
        manufacturerName: "Allergan Inc.",
        manufacturerId: "100000000278",
        amount: 500.0,
        date: "2017-01-27T00:00:00.000Z",
        year: "2017",
        paymentType: "In-kind items and services",
        paymentNature: "Food and Beverage",
        productType: "Drug",
        productCategory: "NEUROSCIENCE",
        productName: "VRAYLAR",
        contextualInfo: null,
      },
      {
        id: "471363572",
        doctorId: "123",
        manufacturerName: "Allergan Inc.",
        manufacturerId: "100000000278",
        amount: 500.0,
        date: "2017-01-27T00:00:00.000Z",
        year: "2017",
        paymentType: "In-kind items and services",
        paymentNature: "Food and Beverage",
        productType: "Drug",
        productCategory: "NEUROSCIENCE",
        productName: "VRAYLAR",
        contextualInfo: null,
      },
    ],
    rank: 1,
    totalAmount: 1000.0,
    topProducts: [],
    topManufacturers: [],
  },
  {
    id: "456",
    firstName: "Jane",
    middleName: null,
    lastName: "Doe",
    addressLine1: "100 Mass Ave",
    addressLine2: null,
    city: "Cambridge",
    state: "MA",
    zipCode: "02139",
    specialty: "Podiatric Medicine & Surgery Service Providers|Podiatrist",
    reviews: [],
    payments: [
      {
        id: "471363573",
        doctorId: "123",
        manufacturerName: "Allergan Inc.",
        manufacturerId: "100000000278",
        amount: 250.0,
        date: "2017-01-27T00:00:00.000Z",
        year: "2017",
        paymentType: "In-kind items and services",
        paymentNature: "Food and Beverage",
        productType: "Drug",
        productCategory: "NEUROSCIENCE",
        productName: "VRAYLAR",
        contextualInfo: null,
      }
    ],
    rank: 1,
    totalAmount: 1000.0,
    topProducts: [],
    topManufacturers: [],
  },
];
